const STATUS_CODES = [
  {
    code: 200,
    name: "OK",
    category: "2xx Success",
    method: "GET",
    path: "/api/status-codes/200",
    description: "Standard success response for GET, POST, PUT, PATCH requests. The request succeeded.",
    scenario: "A client requests a list of users and the server returns them with 200 OK.",
  },
  {
    code: 201,
    name: "Created",
    category: "2xx Success",
    method: "GET",
    path: "/api/status-codes/201",
    description: "Indicates a new resource was successfully created (typically after a POST request).",
    scenario: "A client creates a new user account and the server responds with 201 Created plus the new resource ID.",
  },
  {
    code: 304,
    name: "Not Modified",
    category: "3xx Redirection",
    method: "GET",
    path: "/api/status-codes/304",
    description: "Tells the client the cached response is still valid. No body is returned. Used with conditional headers like If-None-Match or If-Modified-Since.",
    scenario: "A client sends GET /users with If-None-Match header. Data hasn't changed, so server returns 304 and the client uses cached data.",
  },
  {
    code: 400,
    name: "Bad Request",
    category: "4xx Client Error",
    method: "GET",
    path: "/api/status-codes/400",
    description: "The server cannot process the request due to malformed syntax, invalid fields, or missing required parameters.",
    scenario: "A client sends POST /login with an empty email field. The server returns 400 and an error message indicating which field is required.",
  },
  {
    code: 401,
    name: "Unauthorized",
    category: "4xx Client Error",
    method: "GET",
    path: "/api/status-codes/401",
    description: "Authentication is required but was not provided or is invalid. The client must provide valid credentials.",
    scenario: "A client requests GET /profile without sending an Authorization header. The server returns 401 and asks the client to log in.",
  },
  {
    code: 403,
    name: "Forbidden",
    category: "4xx Client Error",
    method: "GET",
    path: "/api/status-codes/403",
    description: "The client is authenticated but does not have permission to access the resource. Unlike 401, the identity is known.",
    scenario: "A user with role 'viewer' tries to access GET /admin. The server knows who they are but denies access with 403.",
  },
  {
    code: 404,
    name: "Not Found",
    category: "4xx Client Error",
    method: "GET",
    path: "/api/status-codes/404",
    description: "The server cannot find the requested resource. The endpoint URL may be wrong or the resource may have been deleted.",
    scenario: "A client requests GET /products/999 but no product with that ID exists. The server returns 404.",
  },
  {
    code: 405,
    name: "Method Not Allowed",
    category: "4xx Client Error",
    method: "GET",
    path: "/api/status-codes/405",
    description: "The HTTP method used is not supported for this endpoint. The response includes an Allow header listing permitted methods.",
    scenario: "A client sends DELETE /api/status-codes/405 but this endpoint only accepts GET. The server returns 405 with Allow: GET header.",
  },
  {
    code: 429,
    name: "Too Many Requests",
    category: "4xx Client Error",
    method: "GET",
    path: "/api/status-codes/429",
    description: "The client has sent too many requests in a given time window. The response includes a Retry-After header.",
    scenario: "A client sends 100 requests per second to a rate-limited endpoint. The server returns 429 with Retry-After: 60.",
  },
  {
    code: 500,
    name: "Internal Server Error",
    category: "5xx Server Error",
    method: "GET",
    path: "/api/status-codes/500",
    description: "A generic error message for unexpected server failures. The server cannot fulfill the request due to an internal issue.",
    scenario: "A database connection pool is exhausted. Any request that needs the database returns 500 until the pool recovers.",
  },
];

export async function GET() {
  return Response.json({
    total: STATUS_CODES.length,
    description:
      "A live demonstration of HTTP status codes. Each endpoint returns the actual HTTP status code in the response so you can see how different statuses look and feel in browser DevTools, curl, or Postman.",
    statusCodes: STATUS_CODES.map((sc) => ({
      code: sc.code,
      name: sc.name,
      category: sc.category,
      path: sc.path,
      description: sc.description,
    })),
  });
}
